namespace Skysemi.With.Enum
{
    public enum EActionCardName
    {
        None = -1,
        Empty = 0,
        Punch = 10,
        Shield = 20,
        Pan = 30,
        MagicAddMaxHp = 40,
        MetalBat = 50,
        StrongPanch = 60,
        StrongShield = 70,
        RoboBlade = 90,
        NasuHeart = 100,
        RingoHeart = 110,
        DaikonHeart = 120,
        BroccoliHeart = 130,
        SuicaHeart = 140,
        HourensouHeart = 145,
        TomatoHeart = 150,
        BladeRoboHeart = 200,
        CameraStabilizerHeart = 210,
        PowerShovelHeart = 220,
        CableReelHeart = 230,
        DorodoroHukaiHeart = 240,
        NiwatoriHeart = 250,
        JusticeLivingSplitHeart = 260,
        JusticeRoboHeart = 270,
        JusticeGroupHeart = 280,
        JusticeRestiveHorseHeart = 290,
        JusticeExecutorHeart = 300,
        GuardPenguin = 310,
    }    
}
